### ISSUE TITLE
A user should be able to access dashboard of analytics (time spent, streak, mood prevalence, history, tribe )

### ISSUE THREAD

**Issue by sarahmango** [kineticflow/kineticflow#17]

**Comment by samjamead** [comment]
Hey @sarahmango I am about to work on this next. Can you define exactly what analytics you want the user to see, and if it's something like e.g. mood prevalence, how should that be calculated... 

I think I know already but just want to be clear :)

**Comment by sarahmango** [comment]
Streak - how many days in a row
Sessions - how many session, how many minutes cumulative total
Graph with day/time on the x bottom axis and moods on the y axis, so you can have an idea about how your moods go over time. Y axis goes happy at the top followed by, ok, tired, stressed, anxious, sad, irritated down to the bottom
Mood pie chart before and after- %mood 

The first couple are the no brainer. I am going to double check with Annika on the last two on her opinion tomorrow, make sure we get the right ones. How fancy can we get?

**Comment by samjamead** [comment]
For v2.0 we can't do fancy which unfortunately means no graphs! 

Graphs can go in v2.1. They can be tricky but not impossible, just time-consuming. 

I'm very sorry but as a qualified Oceanographer I am legally bound to prevent people displaying data in the wrong kind of graph and unfortunately what you described doesn't make sense graphically... But we can save this debate for next week when we start on v2.1 😄 

For v2.0 I am going to go with: 

+ Streak
+ Sessions total 
+ Minutes cumulative 
+ Most frequent starting mood 
+ Activity most frequently prepped for
+ A list of your history (perhaps limited to most recent 10 or so) 

They might be a bit more boring than graphs but they're quicker to implement! 

Don't worry I have designed the database to collect the necessary data to plot the graphs when we get the time.

**Comment by sarahmango** [comment]
Haha, ok. Thank god youre qualified for this :)

But lets also squeeze Most frequent ending mood in, so peeps can see their difference

**Comment by samjamead** [comment]
Good idea, I accept!

**Comment by samjamead** [comment]
Closed by 688cd5c
