### ISSUE TITLE
Streak is calculated incorrectly

### ISSUE THREAD

**Issue by samjamead** [kineticflow/kineticflow#49]
Currently, streak is calculated by subtracting 24 hours from the current time. 

HOWEVER! What if on Tuesday I did my mindfulness in the morning, and on Wednesday I did it in the evening. More than 24 hours have passed, so I lost my streak. But really since I did do mindfulness on consecutive days I should retain my streak! 

@sarahmango the fix for this will be a little bit time consuming, so I am going to de-prioritise. 

In the meantime, should I leave it as 24 hours or extend it to, for example, 36 hours?

**Comment by sarahmango** [comment]
Can we use the date?

**Comment by samjamead** [comment]
Yes but that's the part that will take time... Basically in Javascript time is calculated in milliseconds elapsed since Midnight on Jan 1 1970... So to calculate if the user did a session yesterday, we need to get the time (in milliseconds), subtract the correct number of milliseconds to get to 1 second past midnight that day, then subtract 24 hours of milliseconds, then check if the previous date is before or after that. 

I can and will do it but for the time being I am going to approximate using 36 hours worth of milliseconds 😄

**Comment by samjamead** [comment]
Ok you twisted my arm... It's fixed properly now!

**Comment by sarahmango** [comment]
say whaaaat?! i am so glad i was not involved in that calculation! nice work
