### ISSUE TITLE
Swap out the actual logo for the word Kinetic Flow in top left hand corner of page

### ISSUE THREAD

**Issue by sarahmango** [kineticflow/kineticflow#63]
https://drive.google.com/open?id=0B1TgHAAvV7b7elA4cXpHU0d5Nms

If this doesn't work, let me know

**Comment by samjamead** [comment]
Do you have an 'inverse' logo that I can put on the log in screen?

**Comment by sarahmango** [comment]
Nope, what does that mean?

**Comment by samjamead** [comment]
White text with transparent background (for use on dark backgrounds)
